[project]
name = "codegen-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click",
    "requests",
    "pathlib",
    "algoliasearch",
    "rich",
]
[project.entry-points]
console_scripts = [
    "codegen=codegen.cli:main",
]
